### ISSUE TITLE
Please Fix

### ISSUE THREAD

**Issue by aor980** [cr3ative/homebridge-apcaccess#20]
Getting the following status every second

Polling UPS service failed: TypeError: Cannot read properties of undefined (reading 'trim')
    at APCAccess.parseData (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:161:45)
    at APCAccess.checkBatteryLevel (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:226:34)
    at APCAccess.doPolledChecks (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:241:10)
    at /var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:99:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cr3ative** [comment]
What does apcaccess output for you in the command line?

**Comment by aor980** [comment]
[13/04/2023, 12:29:01] [UPS] Power: Connected
[13/04/2023, 12:29:01] [UPS] Battery state: Normal
[13/04/2023, 12:29:01] [UPS] Charging state: NOT_CHARGING
[13/04/2023, 12:29:01] [UPS] Polling UPS service failed: TypeError: Cannot read properties of undefined (reading 'trim')
    at APCAccess.parseData (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:161:45)
    at APCAccess.checkBatteryLevel (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:226:34)
    at APCAccess.doPolledChecks (/var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:241:10)
    at /var/lib/homebridge/node_modules/homebridge-apcaccess/index.js:99:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cr3ative** [comment]
No mate, the output of `apcaccess` on the command line of the box which it is configured on.

**Comment by aor980** [comment]
Let's pretend I'm an idot, how do I do that?

**Comment by aor980** [comment]
root@DD-WRT:/tmp/home/root# apcaccess
APC      : 001,032,0745
DATE     : 2023-04-13 13:17:02 -0400
HOSTNAME : DD-WRT
VERSION  : 3.14.14 (31 May 2016) debian
UPSNAME  : DD-WRT
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 1969-12-31 19:00:08 -0500
MODEL    : GX1500U
STATUS   : ONLINE
LINEV    : 121.0 Volts
LOADPCT  : 3.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 135.4 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 3 Minutes
MAXTIME  : 0 Seconds
OUTPUTV  : 121.0 Volts
DWAKE    : -1 Seconds
LOTRANS  : 100.0 Volts
HITRANS  : 139.0 Volts
ALARMDEL : 30 Seconds
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
SELFTEST : NO
STATFLAG : 0x05000008
SERIALNO : QA9LT7001219
NOMINV   : 120 Volts
NOMPOWER : 900 Watts
END APC  : 2023-04-13 13:17:08 -0400

**Comment by cr3ative** [comment]
Hm, right, your UPS doesn't report `BATTV`. That doesn't look critical. I'll see what I can do.

**Comment by cr3ative** [comment]
@aor980 Published 1.0.2 - can you give that a try for me?

**Comment by aor980** [comment]
will do.

...and its fixed. Great job.

**Comment by cr3ative** [comment]
wheyyyyyyyy
