### ISSUE TITLE
Unable to change log level

### ISSUE THREAD

**Issue by ThisIsQasim** [cr3ative/homebridge-apcaccess#23]
Getting the following error if I set `errorLogsOnly: true`

```
[APC Smart-UPS] Polling UPS service failed: TypeError: this.log.update.warn is not a function
    at APCAccess.checkContact (/homebridge/node_modules/homebridge-apcaccess/index.js:180:21)
    at APCAccess.doPolledChecks (/homebridge/node_modules/homebridge-apcaccess/index.js:238:10)
    at /homebridge/node_modules/homebridge-apcaccess/index.js:99:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by cr3ative** [comment]
Ah oops. Let me see if I can push an update.

**Comment by cr3ative** [comment]
Published `1.0.3` to clean up that log line specifically, but I feel a refactor of the logging stuff coming on if it continues to be a problem. Give it a go.

**Comment by ThisIsQasim** [comment]
Thanks for the quick response. There is a new error on temperature
```
[9/1/2023, 6:25:38 PM] [homebridge-apcaccess] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: this.log.update.error is not a function. See https://homebridge.io/w/JtMGR for more info.
```

**Comment by cr3ative** [comment]
lol, lmao. Okay, well, I can look at that. In the mean time, your UPS is clearly not happy - try running `apcaccess` on the command line and seeing the status; that has to work first.

**Comment by ThisIsQasim** [comment]
~~`apcaccess` works fine. In fact everything else is working fine except for the temperature sensor.~~

**Comment by ThisIsQasim** [comment]
My bad. The error was indeed from before when there was an issue with `apcaccess`. All good now!

**Comment by cr3ative** [comment]
Gotcha, thanks - that’s useful. And hey, at least it works with logs on! I’ll revise the logging soon.
